"""
Django settings for archive_system project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t-w(3bz153yh6_%9smxi+#od$(u2ij*tbd-y+4yw1-tah%4)lp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'goldfish-banked-valley.ngrok-free.dev']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'eams',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'archive_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'archive_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ط¥ط¹ط¯ط§ط¯ط§طھ CSRF ظ„ط¥طµظ„ط§ط­ ظ…ط´ظƒظ„ط© طھط³ط¬ظٹظ„ ط§ظ„ط¯ط®ظˆظ„ ط¹ط¨ط± ط§ظ„ط´ط¨ظƒط©
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.1.37:8000',
    'http://192.168.1.37:8001',
    'http://192.168.1.37:8002',
    'http://192.168.1.37:8003',
    'http://192.168.1.37:8004',
    'http://192.168.1.37:8005',
    'http://192.168.1.29:8000',
    'http://192.168.1.29:8001',
    'http://192.168.1.29:8002',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
    'https://acquisitions-institutions-matter-watershed.trycloudflare.com',
]

# ط¥ط¹ط¯ط§ط¯ط§طھ CORS ظ„ظ„ط³ظ…ط§ط­ ط¨ط§ظ„ظˆطµظˆظ„ ظ…ظ† ط§ظ„ظ…طھطµظپط­ط§طھ ط§ظ„ط®ط§ط±ط¬ظٹط© (ط§ظ„ظ…ظˆط¨ط§ظٹظ„)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://nqabaalmohamen.github.io",
]

# ط¥ط¹ط¯ط§ط¯ط§طھ ط§ظ„ط¬ظ„ط³ط©
SESSION_COOKIE_NAME = 'archive_sessionid'
CSRF_COOKIE_NAME = 'archive_csrftoken'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 900  # 15 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True

# ============================================================
# ?? إعدادات صفحة المتابعة الخارجية
# ============================================================

# رابط صفحة المتابعة على GitHub Pages (ثابت ودائم - مجاني)
REMOTE_TRACKING_URL = "https://nqabaalmohamen.github.io/archives/"

# رابط Cloudflare Tunnel للـ API (يُحدَّث بعد تشغيل تشغيل_النفق.ps1)
CLOUDFLARE_TUNNEL_URL = "https://acquisitions-institutions-matter-watershed.trycloudflare.com"

ENABLE_REMOTE_SYNC = True


CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
    'cf-skip-browser-warning',
]










