# Generated by Django 4.2.27 on 2026-04-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر'), ('internal', 'داخلي')], default='incoming', max_length=20, verbose_name='نوع الوثيقة'),
        ),
    ]
