# Generated by Django 4.2.27 on 2026-04-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0002_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الصادر/الوارد'),
        ),
    ]
