# Generated by Django 4.2.27 on 2026-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0003_document_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم بالكامل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير نظام'), ('employee', 'موظف'), ('viewer', 'مشاهد')], default='viewer', max_length=20),
        ),
    ]
