# Generated by Django 4.2.27 on 2026-04-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0004_profile_department_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_access_audit_log',
            field=models.BooleanField(default=False, verbose_name='سجل التحركات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_access_categories',
            field=models.BooleanField(default=False, verbose_name='إدارة الأقسام'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_access_documents',
            field=models.BooleanField(default=True, verbose_name='الوصول للوثائق'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_access_reports',
            field=models.BooleanField(default=False, verbose_name='الوصول للتقارير'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='إدارة المستخدمين'),
        ),
    ]
