# Generated by Django 4.2.27 on 2026-04-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0005_profile_can_access_audit_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_access_audit_log',
            new_name='can_view_audit_log',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='can_access_reports',
            new_name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_access_categories',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_access_documents',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_manage_users',
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_cats',
            field=models.BooleanField(default=False, verbose_name='إضافة تصنيفات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_docs',
            field=models.BooleanField(default=False, verbose_name='إضافة وثائق'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_users',
            field=models.BooleanField(default=False, verbose_name='إضافة مستخدمين'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_cats',
            field=models.BooleanField(default=False, verbose_name='حذف تصنيفات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_docs',
            field=models.BooleanField(default=False, verbose_name='حذف وثائق'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_users',
            field=models.BooleanField(default=False, verbose_name='حذف مستخدمين'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_cats',
            field=models.BooleanField(default=False, verbose_name='تعديل تصنيفات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_docs',
            field=models.BooleanField(default=False, verbose_name='تعديل وثائق'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_users',
            field=models.BooleanField(default=False, verbose_name='تعديل مستخدمين'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_cats',
            field=models.BooleanField(default=True, verbose_name='مشاهدة التصنيفات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_docs',
            field=models.BooleanField(default=True, verbose_name='مشاهدة الوثائق'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_users',
            field=models.BooleanField(default=False, verbose_name='مشاهدة المستخدمين'),
        ),
    ]
