# Generated by Django 4.2.27 on 2026-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0006_rename_can_access_audit_log_profile_can_view_audit_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='can_view_audit_log',
            new_name='access_audit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_add_cats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_add_docs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_add_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_delete_cats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_delete_docs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_delete_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_edit_cats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_edit_docs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_edit_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_view_cats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_view_docs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='can_view_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='access_categories',
            field=models.BooleanField(default=False, verbose_name='إدارة الأقسام'),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_incoming',
            field=models.BooleanField(default=True, verbose_name='الأرشيف الوارد'),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_internal',
            field=models.BooleanField(default=True, verbose_name='البريد الداخلي'),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_outgoing',
            field=models.BooleanField(default=True, verbose_name='الأرشيف الصادر'),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_reports',
            field=models.BooleanField(default=False, verbose_name='التقارير الإحصائية'),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_users',
            field=models.BooleanField(default=False, verbose_name='إدارة المستخدمين'),
        ),
    ]
