# Generated by Django 4.2.27 on 2026-05-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0007_rename_can_view_audit_log_profile_access_audit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='كلمة المرور الحالية (للمدير)'),
        ),
    ]
