# Generated by Django 4.2.27 on 2026-05-03 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eams', '0008_profile_raw_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المتابعة')),
                ('current_status', models.CharField(choices=[('received', 'تم الاستلام'), ('under_review', 'تحت المراجعة'), ('sent', 'تم الإرسال'), ('received_from_other', 'تم الاستلام من جهة أخرى'), ('in_progress', 'جاري التنفيذ'), ('completed', 'تم الانتهاء')], default='received', max_length=50, verbose_name='الحالة الحالية')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المعاملة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='eams.transaction', verbose_name='المعاملة (رقم المتابعة)'),
        ),
    ]
