# Generated by Django 4.2.27 on 2026-05-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0009_transaction_document_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recipient_department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قسم المستلم'),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستلم'),
        ),
    ]
