# Generated by Django 4.2.27 on 2026-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0010_document_recipient_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='current_status',
            field=models.CharField(choices=[('received', 'تم الاستلام'), ('under_review', 'تحت المراجعة'), ('sent', 'تم الإرسال'), ('received_from_other', 'تم الاستلام من جهة أخرى'), ('in_progress', 'جاري التنفيذ'), ('completed', 'تم الانتهاء')], default='under_review', max_length=50, verbose_name='الحالة الحالية'),
        ),
    ]
