# Generated by Django 4.2.27 on 2026-05-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0011_alter_transaction_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_name',
            field=models.CharField(default='غير محدد', max_length=255, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_phone',
            field=models.CharField(default='000', max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم القيد (اختياري)'),
        ),
    ]
