# Generated by Django 4.2.27 on 2026-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0012_transaction_client_gender_transaction_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='group_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف المجموعة (للرفع المتعدد)'),
        ),
    ]
