# Generated by Django 4.2.27 on 2026-05-11 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0014_documentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='secure_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='رمز الأمان'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_status',
            field=models.CharField(choices=[('received', 'تم الاستلام'), ('under_review', 'تحت المراجعة'), ('in_progress', 'جاري التنفيذ'), ('completed', 'تم الانتهاء')], default='under_review', max_length=50, verbose_name='الحالة الحالية'),
        ),
    ]
