# Generated by Django 4.2.27 on 2026-05-11 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0015_transaction_secure_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='secure_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز الأمان'),
        ),
    ]
