# Generated by Django 4.2.27 on 2026-05-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0016_alter_transaction_secure_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='current_status',
            field=models.CharField(choices=[('received', 'تم الاستلام'), ('under_review', 'تحت المراجعة'), ('in_progress', 'جاري التنفيذ'), ('completed', 'تم الانتهاء')], default='received', max_length=50, verbose_name='الحالة الحالية'),
        ),
    ]
