# Generated by Django 4.2.27 on 2026-05-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0017_alter_transaction_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='الملف'),
        ),
    ]
