# Generated by Django 4.2.27 on 2026-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0019_alter_transaction_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='missing_info',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات للنواقص (تظهر لصاحب الشأن)'),
        ),
    ]
