# Generated by Django 4.2.27 on 2026-05-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eams', '0020_transaction_missing_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completion_note',
            field=models.TextField(blank=True, null=True, verbose_name='تعليمات الاستلام عند الانتهاء (تظهر لصاحب الشأن)'),
        ),
    ]
